# .github/workflows/on-fork.yml
name: Fork Event Trigger

on:
  fork:

jobs:
  handle-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Log Fork Event
        run: |
          echo "A fork of this repository was created!"
          echo "Forked by: ${{ github.event.forkee.owner.login }}"
          echo "Forked repository URL: ${{ github.event.forkee.html_url }}"
